import { Resource } from '@/types/resources'

export const freeResources: Resource[] = [
  {
    id: 'coming-out-of-rest-mode',
    title: 'Coming Out of Rest Mode',
    subtitle: 'Sustainable Tech for the Long Game — March 2026',
    description: 'Build digital systems that survive real life, not just motivated weeks. The 50% framing and Keep / Drain / Carry audit for neurodivergent brains returning from a break.',
    emoji: '🔥',
    features: [
      '50% framing: the right direction beats the perfect plan',
      'Keep / Drain / Carry audit for your current stack',
      'Event replay: Coming Out of Rest Mode, March 29, 2026',
    ],
    href: '/coming-out-of-rest-mode',
    borderColor: 'green',
    type: 'free',
  },
  {
    id: 'digital-spring-cleaning',
    title: 'Digital Spring Cleaning',
    subtitle: 'Grit Framework Toolkit — April 2026',
    description: 'Four layers of digital spring cleaning for neurodivergent brains: energy audit, Now / Soon / Reference file structure, attention and notification hygiene, and maintenance rhythms that hold on hard days.',
    emoji: '🌱',
    features: [
      'Grit Framework check-in (Passion, Perseverance, Growth, Resilience)',
      'NAA reset, friction-maxxing, and fail-soft maintenance',
      'Monthly Grit Reflection Worksheet (PDF + Canva)',
    ],
    href: '/digital-spring-cleaning',
    downloadHref: '/digital-spring-cleaning/grit-workflow-worksheet-2026-fire-horse-edition.pdf',
    downloadLabel: 'Download 2026 Workbook',
    borderColor: 'green',
    type: 'free',
  },
  {
    id: 'mindful-automation',
    title: 'Mindful Automation',
    subtitle: 'Y.O.U.R. Framework System — May 2026',
    description: 'Build automation that works for your brain and reaches the people on the other end. The Y.O.U.R. Framework plus O.U.R. Context files, Maya client thread, and IDE workbench deep dives.',
    emoji: '⚙️',
    features: [
      'Y.O.U.R. Framework + O.U.R. Context',
      'Self-audit, journey map, and context starter worksheets',
      'May 2026 newsletter arc + Lab Notes',
    ],
    href: '/mindful-automation',
    downloadHref: '/mindful-automation/your-self-audit-worksheet.pdf',
    downloadLabel: 'Download Self-Audit Worksheet (PDF)',
    borderColor: 'green',
    type: 'free',
  },
  {
    id: 'accessible-tech-design',
    title: 'Accessible Tech Design',
    subtitle: 'Five-Fix Guide',
    description:
      'Self-guided five-fix accessibility arc with checklist PDF — work through contrast, structure, alt text, captions, and honest links in 15-minute steps.',
    emoji: '♿',
    features: [
      'Self-guided fix walkthroughs on one page',
      'Fix 1: Readable contrast',
      'Fix 2: Scannable structure',
      'Fix 3: Alt text workflow',
      'Fix 4: Video & audio inclusion',
      'Fix 5: Honest links & flows',
      'Free Accessible Tech Checklist (PDF)',
    ],
    href: '/accessible-tech-design',
    downloadHref: '/accessible-tech-design/accessible-tech-checklist-2026.pdf',
    downloadLabel: 'Download Accessible Tech Checklist (PDF)',
    borderColor: 'green',
    type: 'free',
  },
  {
    id: 'neuroinclusive-design',
    title: 'Neuroinclusive Design',
    subtitle: 'June 2025 Deep Dive',
    description: 'Learn how designing for neurodivergent users creates better experiences for everyone—moving beyond accommodation to proactive inclusion with practical principles and tools.',
    emoji: '🧠',
    features: [
      'Four Core Design Principles',
      'Five-Minute Accessibility Check',
      'Weekly Deep Dives & Newsletter Links',
    ],
    href: '/neuroinclusive-design',
    borderColor: 'green',
    type: 'free',
  },
  {
    id: 'tech-boundaries',
    title: 'Tech Boundaries',
    subtitle: 'July 2025 Deep Dive',
    description: 'Small boundaries, big energy gains—learn to create digital systems that work with your brain, not against it. Transform tech overwhelm into creative fuel.',
    emoji: '⚡',
    features: [
      'Three Core Boundary Pillars',
      'PARA Method & Energy-Aware Automation',
      'Weekly Deep Dives & Newsletter Links',
    ],
    href: '/tech-boundaries',
    borderColor: 'green',
    type: 'free',
  },
  {
    id: 'vibe-coding-cheatsheet',
    title: 'Vibe Coding Cheatsheet',
    subtitle: 'Interactive Developer Resource',
    description:
      'Copy-ready prompts and Tailwind examples for neurodivergent-friendly coding workflows.',
    emoji: '💻',
    features: [
      'Interactive TailwindCSS Examples',
      'Copy-to-Clipboard Functionality',
      'Professional Development Patterns',
    ],
    href: '/vibe-coding-cheatsheet',
    borderColor: 'green',
    type: 'free',
  },
  {
    id: 'password-security',
    title: 'Password Security Guide',
    subtitle: 'Complete User Guide',
    description: 'Your complete guide to password security and two-factor authentication. Learn how to manage dozens of passwords without losing your mind, choose the right password manager, and set up 2FA without anxiety.',
    emoji: '🔐',
    features: [
      '30-Day Password Security Roadmap',
      'Password Manager Comparison & Recommendations',
      'Two-Factor Authentication Setup Guide',
      'Priority-Based Account Security Strategy',
    ],
    href: '/passwords',
    borderColor: 'purple',
    type: 'free',
  },
  {
    id: 'privacy-pleasure',
    title: 'Privacy Pleasure',
    subtitle: '4-Week Journey to Digital Independence',
    description: 'Building digital independence (slowly) in a world where billionaires monetize every click. A complete guide to password security, VPN protection, secure communication, and building your complete privacy system.',
    emoji: '🛡️',
    features: [
      'Week 1: Password Foundation',
      'Week 2: ISP & VPN Protection',
      'Week 3: Secure Communication & File Sharing',
      'Week 4: Your Complete System',
    ],
    href: '/privacy-pleasure',
    borderColor: 'green',
    type: 'free',
  },
  {
    id: 'ai-mythbusting',
    title: 'AI Myth-Busting',
    subtitle: 'Critical Thinking Toolkit',
    description: "From the Wooden Snake's wisdom to bullshit detection: understand what AI actually is, what it isn't, and how to use it responsibly in our tech-power-government era.",
    emoji: '🧠',
    features: [
      'Three Core AI Myths Debunked',
      'Critical Thinking Framework',
      'Free AI Learning Resources',
    ],
    href: '/ai-mythbusting',
    borderColor: 'purple',
    type: 'free',
  },
  {
    id: 'accessibility',
    title: 'Digital Accessibility Legal Guide',
    subtitle: 'Starting Point for Business Owners',
    description: 'Essential starting guide to digital accessibility laws, compliance requirements, and practical implementation for business owners. Legal framework, risk management, and actionable first steps.',
    emoji: '⚖️',
    features: [
      'Four Simple Tests You Can Do Right Now',
      '90-Day Implementation Plan',
      'Legal Framework & Compliance Requirements',
      'Free Testing Tools & Resources',
    ],
    href: '/accessibility',
    borderColor: 'purple',
    type: 'free',
  },
  {
    id: 'back-to-basics',
    title: 'Back to Basics',
    subtitle: 'Digital Organization & AI-Ready Workflows',
    description: "Master the fundamental tech skills that make AI tools actually useful instead of frustrating. Build the foundation that supports your creativity with the Wooden Snake's wisdom.",
    emoji: '🏗️',
    features: [
      'The 3-Folder Rule for Digital Organization',
      'Creative Workflow Revolution',
      'Data Flow from Chaos to Conscious',
      'Basic Automation That Serves Creativity',
    ],
    href: '/back-to-basics',
    borderColor: 'green',
    type: 'free',
  },
  {
    id: 'sourdough',
    title: 'Sourdough Corner',
    subtitle: 'Craft Baking Resources',
    description: "Comprehensive sourdough baking guide with recipes, techniques, and Amanda's favorite tools. Perfect for beginners and experienced bakers alike.",
    emoji: '🍞',
    features: [
      'Starter Creation & Maintenance',
      'Lazy Double Batch Recipe',
      'Tool Recommendations & Resources',
    ],
    href: '/sourdough',
    borderColor: 'green',
    type: 'free',
  },
]

