import { Resource } from '@/types/resources'

export const freeResources: Resource[] = [
  {
    id: 'digital-spring-cleaning',
    title: 'Digital Spring Cleaning',
    subtitle: 'GRIT Framework Toolkit',
    description: 'A comprehensive 4-page worksheet designed to help you refresh your digital life using the GRIT framework (Passion, Perseverance, Growth, Resilience). Perfect for monthly or quarterly reflection.',
    emoji: '🌱',
    features: [
      'Digital Spring Cleaning Worksheet (PDF)',
      'Interactive Canva Template',
      'NAA Framework Guide (Notice, Adjust, Acknowledge)',
    ],
    href: '/digital-spring-cleaning',
    downloadHref: '/digital-spring-cleaning/digitalspringcleaningWorksheet.pdf',
    downloadLabel: 'Download PDF',
    borderColor: 'green',
    type: 'free',
  },
  {
    id: 'mindful-automation',
    title: 'Mindful Automation',
    subtitle: 'Y.O.U. Framework System',
    description: 'Learn to build automation systems that work with your unique brain patterns. The Y.O.U. Framework (Your Brain, Optimize Energy, Understand Maintenance) creates sustainable, brain-friendly workflows.',
    emoji: '⚙️',
    features: [
      'Y.O.U. Framework Guide (PDF)',
      'Error-Proofing Worksheet',
      'Weekly Deep Dive Resources',
    ],
    href: '/mindful-automation',
    downloadHref: '/mindful-automation/youframework.pdf',
    downloadLabel: 'Download PDF',
    borderColor: 'green',
    type: 'free',
  },
  {
    id: 'neuroinclusive-design',
    title: 'Neuroinclusive Design',
    subtitle: 'June 2025 Deep Dive',
    description: 'Learn how designing for neurodivergent users creates better experiences for everyone—moving beyond accommodation to proactive inclusion with practical principles and tools.',
    emoji: '🧠',
    features: [
      'Four Core Design Principles',
      'Five-Minute Accessibility Check',
      'Weekly Deep Dives & Newsletter Links',
    ],
    href: '/neuroinclusive-design',
    borderColor: 'green',
    type: 'free',
  },
  {
    id: 'tech-boundaries',
    title: 'Tech Boundaries',
    subtitle: 'July 2025 Deep Dive',
    description: 'Small boundaries, big energy gains—learn to create digital systems that work with your brain, not against it. Transform tech overwhelm into creative fuel.',
    emoji: '⚡',
    features: [
      'Three Core Boundary Pillars',
      'PARA Method & Energy-Aware Automation',
      'Weekly Deep Dives & Newsletter Links',
    ],
    href: '/tech-boundaries',
    borderColor: 'green',
    type: 'free',
  },
  {
    id: 'vibe-coding-cheatsheet',
    title: 'Vibe Coding Cheatsheet',
    subtitle: 'Interactive Developer Resource',
    description: 'A professional showcase of TailwindCSS techniques with interactive features. Perfect for developers looking to level up their styling game with copy-to-clipboard functionality.',
    emoji: '💻',
    features: [
      'Interactive TailwindCSS Examples',
      'Copy-to-Clipboard Functionality',
      'Professional Development Patterns',
    ],
    href: '/vibe-coding-cheatsheet',
    borderColor: 'green',
    type: 'free',
  },
  {
    id: 'password-security',
    title: 'Password Security Guide',
    subtitle: 'Complete User Guide',
    description: 'Your complete guide to password security and two-factor authentication. Learn how to manage dozens of passwords without losing your mind, choose the right password manager, and set up 2FA without anxiety.',
    emoji: '🔐',
    features: [
      '30-Day Password Security Roadmap',
      'Password Manager Comparison & Recommendations',
      'Two-Factor Authentication Setup Guide',
      'Priority-Based Account Security Strategy',
    ],
    href: '/passwords',
    borderColor: 'purple',
    type: 'free',
  },
  {
    id: 'privacy-pleasure',
    title: 'Privacy Pleasure',
    subtitle: '4-Week Journey to Digital Independence',
    description: 'Building digital independence (slowly) in a world where billionaires monetize every click. A complete guide to password security, VPN protection, secure communication, and building your complete privacy system.',
    emoji: '🛡️',
    features: [
      'Week 1: Password Foundation',
      'Week 2: ISP & VPN Protection',
      'Week 3: Secure Communication & File Sharing',
      'Week 4: Your Complete System',
    ],
    href: '/privacy-pleasure',
    borderColor: 'green',
    type: 'free',
  },
  {
    id: 'ai-mythbusting',
    title: 'AI Myth-Busting',
    subtitle: 'Critical Thinking Toolkit',
    description: "From the Wooden Snake's wisdom to bullshit detection: understand what AI actually is, what it isn't, and how to use it responsibly in our tech-power-government era.",
    emoji: '🧠',
    features: [
      'Three Core AI Myths Debunked',
      'Critical Thinking Framework',
      'Free AI Learning Resources',
    ],
    href: '/ai-mythbusting',
    borderColor: 'purple',
    type: 'free',
  },
  {
    id: 'accessibility',
    title: 'Digital Accessibility Legal Guide',
    subtitle: 'Starting Point for Business Owners',
    description: 'Essential starting guide to digital accessibility laws, compliance requirements, and practical implementation for business owners. Legal framework, risk management, and actionable first steps.',
    emoji: '⚖️',
    features: [
      'Four Simple Tests You Can Do Right Now',
      '90-Day Implementation Plan',
      'Legal Framework & Compliance Requirements',
      'Free Testing Tools & Resources',
    ],
    href: '/accessibility',
    borderColor: 'purple',
    type: 'free',
  },
  {
    id: 'back-to-basics',
    title: 'Back to Basics',
    subtitle: 'Digital Organization & AI-Ready Workflows',
    description: "Master the fundamental tech skills that make AI tools actually useful instead of frustrating. Build the foundation that supports your creativity with the Wooden Snake's wisdom.",
    emoji: '🏗️',
    features: [
      'The 3-Folder Rule for Digital Organization',
      'Creative Workflow Revolution',
      'Data Flow from Chaos to Conscious',
      'Basic Automation That Serves Creativity',
    ],
    href: '/back-to-basics',
    borderColor: 'green',
    type: 'free',
  },
  {
    id: 'sourdough',
    title: 'Sourdough Corner',
    subtitle: 'Craft Baking Resources',
    description: "Comprehensive sourdough baking guide with recipes, techniques, and Amanda's favorite tools. Perfect for beginners and experienced bakers alike.",
    emoji: '🍞',
    features: [
      'Starter Creation & Maintenance',
      'Lazy Double Batch Recipe',
      'Tool Recommendations & Resources',
    ],
    href: '/sourdough',
    borderColor: 'green',
    type: 'free',
  },
]

