[build]
  command = "next build"
  publish = "out"

[build.environment]
  NODE_VERSION = "18"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[build.cache]
  paths = [
    "node_modules/.cache",
    ".next/cache",
    "public/feed.xml"
  ]
